import { MD3LightTheme } from 'react-native-paper';

export const customColors = {
  primary: '#4A90E2',
  secondary: '#7FDBB6',
  background: '#FFFFFF',
  surface: '#F8F9FA',
  error: '#FF6B6B',
  text: '#2C3E50',
  textSecondary: '#34495E',
  textLight: '#7F8C8D',
  disabled: '#BDC3C7',
  placeholder: '#95A5A6',
  border: '#E9ECEF',
  success: '#27AE60',
  warning: '#F39C12',
  info: '#3498DB',
  // Colores específicos para embarazo
  pregnancyPink: '#FFB6C1',
  babyBlue: '#87CEEB',
  softYellow: '#FFFACD',
  neutralGray: '#F5F5F5',
};

export const theme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: customColors.primary,
    secondary: customColors.secondary,
    background: customColors.background,
    surface: customColors.surface,
    error: customColors.error,
    onPrimary: '#FFFFFF',
    onSecondary: '#FFFFFF',
    onBackground: customColors.text,
    onSurface: customColors.text,
    onSurfaceVariant: customColors.textSecondary,
    onError: '#FFFFFF',
    outline: customColors.border,
    outlineVariant: customColors.border,
    scrim: 'rgba(0, 0, 0, 0.32)',
    shadow: 'rgba(0, 0, 0, 0.15)',
    inverseOnSurface: '#F8F9FA',
    inverseSurface: '#2C3E50',
    inversePrimary: '#4A90E2',
    surfaceDisabled: customColors.disabled,
    onSurfaceDisabled: customColors.textLight,
    surfaceContainer: '#FFFFFF',
    surfaceContainerHighest: '#FFFFFF',
    surfaceContainerHigh: '#F8F9FA',
    surfaceContainerLow: '#FFFFFF',
    surfaceContainerLowest: '#FFFFFF',
    surfaceBright: '#FFFFFF',
    surfaceDim: '#F8F9FA',
  },
  fonts: {
    ...MD3LightTheme.fonts,
    bodyLarge: {
      fontFamily: 'System',
      fontSize: 16,
      fontWeight: '400' as const,
      letterSpacing: 0.5,
      lineHeight: 24,
      color: customColors.text,
    },
    bodyMedium: {
      fontFamily: 'System',
      fontSize: 14,
      fontWeight: '400' as const,
      letterSpacing: 0.25,
      lineHeight: 20,
      color: customColors.text,
    },
    bodySmall: {
      fontFamily: 'System',
      fontSize: 12,
      fontWeight: '400' as const,
      letterSpacing: 0.4,
      lineHeight: 16,
      color: customColors.textSecondary,
    },
    titleLarge: {
      fontFamily: 'System',
      fontSize: 22,
      fontWeight: '600' as const,
      letterSpacing: 0,
      lineHeight: 28,
      color: customColors.text,
    },
    titleMedium: {
      fontFamily: 'System',
      fontSize: 18,
      fontWeight: '600' as const,
      letterSpacing: 0,
      lineHeight: 24,
      color: customColors.text,
    },
    titleSmall: {
      fontFamily: 'System',
      fontSize: 16,
      fontWeight: '600' as const,
      letterSpacing: 0.1,
      lineHeight: 20,
      color: customColors.text,
    },
    labelLarge: {
      fontFamily: 'System',
      fontSize: 14,
      fontWeight: '600' as const,
      letterSpacing: 0.1,
      lineHeight: 20,
      color: customColors.text,
    },
    labelMedium: {
      fontFamily: 'System',
      fontSize: 12,
      fontWeight: '600' as const,
      letterSpacing: 0.5,
      lineHeight: 16,
      color: customColors.textSecondary,
    },
    labelSmall: {
      fontFamily: 'System',
      fontSize: 11,
      fontWeight: '600' as const,
      letterSpacing: 0.5,
      lineHeight: 16,
      color: customColors.textLight,
    },
    headlineLarge: {
      fontFamily: 'System',
      fontSize: 32,
      fontWeight: '700' as const,
      letterSpacing: 0,
      lineHeight: 40,
      color: customColors.text,
    },
    headlineMedium: {
      fontFamily: 'System',
      fontSize: 28,
      fontWeight: '700' as const,
      letterSpacing: 0,
      lineHeight: 36,
      color: customColors.text,
    },
    headlineSmall: {
      fontFamily: 'System',
      fontSize: 24,
      fontWeight: '700' as const,
      letterSpacing: 0,
      lineHeight: 32,
      color: customColors.text,
    },
    displayLarge: {
      fontFamily: 'System',
      fontSize: 57,
      fontWeight: '700' as const,
      letterSpacing: -0.25,
      lineHeight: 64,
      color: customColors.text,
    },
    displayMedium: {
      fontFamily: 'System',
      fontSize: 45,
      fontWeight: '700' as const,
      letterSpacing: 0,
      lineHeight: 52,
      color: customColors.text,
    },
    displaySmall: {
      fontFamily: 'System',
      fontSize: 36,
      fontWeight: '700' as const,
      letterSpacing: 0,
      lineHeight: 44,
      color: customColors.text,
    },
  },
  roundness: 12,
}; 